### ISSUE TITLE
Running 

### ISSUE THREAD

**Issue by wolff** [thomaswilley/pelicanyan#1]
Running 

`python -m SimpleHTTPServer` while in the content folder produces HTML such as 

 `<link rel="stylesheet" href="/theme/css/poole.css"/>`

Is this the desired behavior? It seems like the /theme/ is hardcoded in the template files. For example in `base.html` but the instructions tell you to clone the GitHub repo and point `THEME` to that repo's directory. 

Thanks in advance -- this looks awesome!

**Comment by thomaswilley** [comment]
Thanks for the feedback.

Pelican itself stores compiled theme outputs to {{ SITEURL }}/theme/ as far as I know. For example you'll see href's including /theme/ on getpelican.com itself.

I haven't played with trying to change where pelican stores the compiled output from the theme but it may be a setting within pelicanconf.py. Admittedly I'm not a Pelican pro, but if you really wanted to locate the theme's compiled output to a different directory perhaps you could add a variable to pelicanconf.py i.e., THEME_DIR='xyz/', update the templates' inclusive hrefs to "{{ SITEURL }}/{{ THEME_DIR}}/..." and then edit your makefile or deploy scripts to modify the output directory itself.

In case part of your question was related to the leading "/", you can set the SITEURL variable within your pelicanconf.py and it will prepend its value into those hrefs during compilation.

**Comment by wolff** [comment]
I most likely am missing something huge then. I didn't realize I needed to manually create a /themes/ directory. If one should be created, it isn't. 

Again I'm likely missing some core concept to themes with Pelican. Sorry in advance for the troubles.

**Comment by thomaswilley** [comment]
You don't need to create that theme/ directory. Pelican generates it under output/ for you (i.e., after running [$ make clean && make html]) with a properly configured pelicanconf.py.

**Comment by wolff** [comment]
Interesting. No `theme` directory was created for me. 

Again, I feel like I must be missing something **huge**
WARNING: Feeds generated without SITEURL set properly may not be valid
ERROR: Skipping output/archives.html: could not find information about 'date'
ERROR: Skipping output/authors.html: could not find information about 'date'
ERROR: Skipping output/categories.html: could not find information about 'date'
ERROR: Skipping output/index.html: could not find information about 'date'
ERROR: Skipping output/my-super-post.html: could not find information about 'date'
ERROR: Skipping output/tags.html: could not find information about 'date'
ERROR: Skipping output/author/alexis-metaireau.html: could not find information about 'date'
ERROR: Skipping output/author/conan-doyle.html: could not find information about 'date'
ERROR: Skipping output/category/python.html: could not find information about 'date'
ERROR: Skipping output/pages/a-pelican-blog-authors.html: could not find information about 'date'
ERROR: Skipping output/pages/a-pelican-blog-awesome.html: could not find information about 'date'
ERROR: Skipping output/pages/a-pelican-blog.html: could not find information about 'date'
ERROR: Skipping output/tag/pelican.html: could not find information about 'date'
ERROR: Skipping output/tag/publishing.html: could not find information about 'date'

**Comment by thomaswilley** [comment]
It looks like your pelicanconf.py has missing/invalid setting(s) in general.

I thought it would probably help more people if I went thru a complete example and so I've done that and will push an updated readme shortly with a start-to-finish install of a sample blog with the theme. I'd suggest you try running thru that - it only takes a few minutes and after doing it you'll probably spot the gap. That said, here's the sample blog's valid pelicanconf.py which you can compare to your own. Particularly the "date" setting perhaps?

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = 'me'
SITENAME = 'sample blog'
SITEURL = ''

PATH = 'content'

TIMEZONE = 'Europe/Paris'

DEFAULT_LANG = 'en'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Pelican', 'http://getpelican.com/'),
         ('Python.org', 'http://python.org/'),
         ('Jinja2', 'http://jinja.pocoo.org/'),
         ('You can modify those links in your config file', '#'),)

# Social widget
SOCIAL = (('You can add links in your config file', '#'),
          ('Another social link', '#'),)

DEFAULT_PAGINATION = False

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True

THEME = 'pelicanyan'
GA_ACCOUNT = 'UA-12344321-1'
TWITTER_ACCOUNT = 'getpelican'
DIRECT_TEMPLATES = ('index', 'categories', 'authors', 'archives', 'sitemap', 'robots', 'humans')
ROBOTS_SAVE_AS = 'robots.txt'
HUMANS_SAVE_AS = 'humans.txt'
SITEMAP_SAVE_AS = 'sitemap.xml'
DEFAULT_LANG = 'en'
DATE_FORMATS = { 'en': '%B %d, %Y', }
STATIC_PATHS = ['images', 'favicon.ico']
SITEDESCRIPTION = 'sample blog'
TYPOGRIFY=True
```

And finally in the off chance this has anything to do with versions, here's a pip3 freeze on the sample blog example:

```
Jinja2==2.7.3
Markdown==2.5.2
MarkupSafe==0.23
Pygments==2.0.1
Unidecode==0.04.17
blinker==1.3
docutils==0.12
feedgenerator==1.7
pelican==3.5.0
python-dateutil==2.3
pytz==2014.10
six==1.9.0
smartypants==1.8.6
typogrify==2.0.7
```

**Comment by wolff** [comment]
#Thank you so much#

I'm not sure what in particular was the problem, but I kinda looked over and added some more settings based on what you wrote and I think I'm pretty much there now. I now see the proper stylesheets, etc, when I make clean && make html.

Thank you again for taking the time to actually dump your pelicanconf.py!
