### ISSUE TITLE
summary instead of full article

### ISSUE THREAD

**Issue by andrewdunndev** [thomaswilley/pelicanyan#4]
Is there a setting to only show a summary of the article rather than have the body render each entire article in full?

**Comment by thomaswilley** [comment]
Not that I'm aware of offhand

**Comment by dhimmel** [comment]
In `templates/index.html` change the line

```
    {{ article.content }}
```

to

```
    {{ article.summary }}
```

I [did this](https://github.com/dhimmel/blog/commit/a7a7bffaf89974ebeec3dda05782c298a0fb22dd#diff-03c9cd1ab9273c97b22a68e04b03c2ac) for my blog. One issue is that readers get confused on how to access the full text. Perhaps adding a "Read more" link at the bottom would resolve this issue.

**Comment by andrewdunndev** [comment]
@dhimmel wow, thanks. I had just forked @thomaswilley repo and was working through an adaptation myself. Didn't think I'd get such a fast and accurate response out of a fairly malformed question.
